# הגדרות Netlify
[build]
  publish = "dist"
  command = "npm run build"

# הפעלת Netlify Identity
[context.production]
  environment = { NETLIFY_IDENTITY_ENABLED = "true" }

# הגדרות משתני סביבה לפרודקשן
[build.environment]
  # משתני סביבה יוגדרו בממשק Netlify
  # VITE_OPENAI_API_KEY = "your_api_key_here"
  # VITE_AI_MODEL = "gpt-3.5-turbo"
  # VITE_AI_MAX_TOKENS = "1000"
  # VITE_AI_TEMPERATURE = "0.7"

# הגדרות עבור שרת ה-proxy המקומי
[dev]
  framework = "vite"
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"
  autoLaunch = true

# הגדרות עבור ממשק הניהול
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# הגדרות עבור קבצי מדיה
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

# הגדרת ברירת מחדל לכל הנתיבים האחרים
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
